on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "<h1>It's great to have your feedback on this project! </h1> We will endeavour to get back to you soon, Thank you! :nerd_face:"
          pr-message: "<h1>Thank you for contributing to this project, your support is much appreciated. </h1> Thank you again and welcome to the community. :nerd_face:"
          footer: "Stay awesome!"
